### PR TITLE
Counter functionality added also for lazy mode

### PR DESCRIPTION
**Pull request by mariusmoldovan**

### CODE REVIEW

**Review by bbliem — CHANGES_REQUESTED** [review]
applications/graph_problems/dominating_set/lazy_cardinality.lp

Please add #show statements (and don't forget to show childItem and childAuxItem) for efficiency. That is, we show item, auxItem, childItem and childAuxItem.


applications/graph_problems/dominating_set/lazy_cost.lp

Again please add #show.

Also, as already discussed, please do not hard-code the arbitrary value 50 as the maximum cost into the encoding. Instead, assume that the maximum cost is given in the input. One possibility of doing this: Use "#external childCost(0..C) : maxCost(C)" and make sure that a maxCost/1 fact is supplied in the input). Alternatively use "#external childCost(0..C) : C = #count { V : vertex(V) }". This would be nicer, but I think this could lead to problems because only those vertex facts whose argument is in the current bag may be provided to the encoding.

Please remove the empty last line.


applications/graph_problems/dominating_set/lazy_costInc.lp

Please rename to lazy_cost_inc.lp or similar.

Please add #show.


applications/graph_problems/vertex_cover/lazy-manual-join.lp

Please remove empty last line(s).

Please add #show.

Cost bound: See above.


applications/graph_problems/vertex_cover/lazy.lp

Please add #show.

Cost bound: See above.


applications/test_opt_counting.sh

Please revert changes.


applications/test_optval.sh

Please revert changes.


src/solver/asp/AtomIntroductionSolver.cpp

Please revert changes.


src/solver/clasp/Solver.cpp

Please add removed TODOs (previously at lines 77 and 137) again.

Fix indentation at line 135.


src/solver/clasp/SolverFactory.cpp

Is there a reason for line 59? There are after all encodings that use cardinality costs but not lazy mode (e.g., applications/graph_problems/dominating_set/exchange.lp).

Please add removed TODO again (previously at line 68).


src/solver/default_join/Solver.cpp

Please revert changes.


src/solver/lazy_clasp/GringoOutputProcessor.cpp

Remove line 98.


src/solver/lazy_clasp/GringoOutputProcessor.h

Please remove tab at line 52.

Observe that the alignment in lines 82-90 is fucked up. Please replace all tabs in these lines (except for the respective first one) by spaces so that the alignment is as in the original code. The same holds for lines 94-102 and 107-115.


src/solver/lazy_clasp/Solver.cpp

Please change lines 189-190 back the way they were (formerly 158-161). (By the way, observe that the new indentation would be messed up.)

Please fix indentation at lines 222-225. By the way, this is messed up because you mixed spaces and tabs. I hope this has not occurred elsewhere.

Is there a reason that auxItemAtomInfos.clear() (formerly on line 221) is removed? Maybe things can go wrong without it?

Please remove empty line 437.


src/solver/lazy_clasp/Solver.h

Please replace lines 61-69 by:

	struct pair_hash
	{
		template <class T1, class T2>
		std::size_t operator()(std::pair<T1,T2> const& p) const
		{
			auto h1 = std::hash<T1>{}(p.first);
			auto h2 = std::hash<T2>{}(p.second);
			return h1^h2;
		}
	};
	typedef std::unordered_map<std::pair<std::string,long>, size_t, pair_hash> CounterMap;

Please replace all remaining occurrences of Custom_Map by CounterMap.

Please fix alignment in lines 72-83. Don't use tabs here (except the very first one in each line for the indentation).


src/solver/lazy_default_join/Solver.cpp

Please put former lines 77 and 96 back in.


src/tinyxml2.h

Please revert changes.

**Comment by mariusmoldovan** [comment]
*Hallo Bernhard,*
*Meine Antworten inline kursiv:*

applications/graph_problems/dominating_set/lazy_cardinality.lp

Please add #show statements (and don't forget to show childItem and
childAuxItem) for efficiency. That is, we show item, auxItem, childItem and
childAuxItem.

*done*

applications/graph_problems/dominating_set/lazy_cost.lp

Again please add #show.

Also, as already discussed, please do not hard-code the arbitrary value 50
as the maximum cost into the encoding. Instead, assume that the maximum
cost is given in the input. One possibility of doing this: Use "#external
childCost(0..C) : maxCost(C)" and make sure that a maxCost/1 fact is
supplied in the input). Alternatively use "#external childCost(0..C) : C =
#count { V : vertex(V) }". This would be nicer, but I think this could lead
to problems because only those vertex facts whose argument is in the
current bag may be provided to the encoding.

Please remove the empty last line.

*done: I used the first possibility. However, I can make sure in the
encoding that input instances will have a maxCost/1 fact*

applications/graph_problems/dominating_set/lazy_costInc.lp

Please rename to lazy_cost_inc.lp or similar.

Please add #show.

*done*

applications/graph_problems/vertex_cover/lazy-manual-join.lp

Please remove empty last line(s).

Please add #show.

Cost bound: See above.

*done*

applications/graph_problems/vertex_cover/lazy.lp

Please add #show.

Cost bound: See above.

*done*

applications/test_opt_counting.sh

Please revert changes.

*done*

applications/test_optval.sh

Please revert changes.

*done*

src/solver/asp/AtomIntroductionSolver.cpp

Please revert changes.

*done*

src/solver/clasp/Solver.cpp

Please add removed TODOs (previously at lines 77 and 137) again.

Fix indentation at line 135.

*done: I had removed the TODOs because you told me I should make sure there
are no more TODOs. I put them back in now.*

src/solver/clasp/SolverFactory.cpp

Is there a reason for line 59? There are after all encodings that use
cardinality costs but not lazy mode (e.g., applications/graph_problems/
dominating_set/exchange.lp).

*I think you are right. I removed it (but was not able to test it).*

Please add removed TODO again (previously at line 68).

*done*

src/solver/default_join/Solver.cpp

Please revert changes.

*done*

src/solver/lazy_clasp/GringoOutputProcessor.cpp

Remove line 98.

*done*

src/solver/lazy_clasp/GringoOutputProcessor.h

Please remove tab at line 52.

Observe that the alignment in lines 82-90 is fucked up. Please replace all
tabs in these lines (except for the respective first one) by spaces so that
the alignment is as in the original code. The same holds for lines 94-102
and 107-115.

*why do tabs fuck up the alignment on git but not on any program I use on
my PC?*

src/solver/lazy_clasp/Solver.cpp

Please change lines 189-190 back the way they were (formerly 158-161). (By
the way, observe that the new indentation would be messed up.)

Please fix indentation at lines 222-225. By the way, this is messed up
because you mixed spaces and tabs. I hope this has not occurred elsewhere.

*could not find any spaces. Just missing tabs on line 225. BTW, I use
copy-paste to make sure there are tabs in the whole program. Just pressing
tab does not make it look the way you initially formatted it in any program
on this PC.*

Is there a reason that auxItemAtomInfos.clear() (formerly on line 221) is
removed? Maybe things can go wrong without it?

*that was a mistake. Not sure what its role is though. I added .clear()
also for the other vectors and maps. could not test it though.*

Please remove empty line 437.

*done*

src/solver/lazy_clasp/Solver.h

Please replace lines 61-69 by:

struct pair_hash
{
	template <class T1, class T2>
	std::size_t operator()(std::pair<T1,T2> const& p) const
	{
		auto h1 = std::hash<T1>{}(p.first);
		auto h2 = std::hash<T2>{}(p.second);
		return h1^h2;
	}
};
typedef std::unordered_map<std::pair<std::string,long>, size_t,
pair_hash> CounterMap;

Please replace all remaining occurrences of Custom_Map by CounterMap.

Please fix alignment in lines 72-83. Don't use tabs here (except the very
first one in each line for the indentation).

*done*

src/solver/lazy_default_join/Solver.cpp

Please put former lines 77 and 96 back in.

*done*

src/tinyxml2.h

Please revert changes.

*don.*


*Please check that it complies and that it works in the desired way
(especially lazy mode - regarding having added .clear() and having removed
the condition for cardinality cost. (As I changed my files to comply with
your folder structure Iḿ not able to compile it anymore)*

*Thanks & BR,*

*Marius*

>

**Review by bbliem — CHANGES_REQUESTED** [review]
Thank you for your changes.


>  I had removed the TODOs because you told me I should make sure there are no
>  more TODOs. I put them back in now.*

Thanks. I was unfortunately not clear on this -- I did not want you to remove all the TODOs that *I* introduced at some point. I could have changed those myself.


>  *why do tabs fuck up the alignment on git but not on any program I use on my
>  PC?*

My guess is that on your editor the tab width is set to something that looks nice to you, but not in editors set to a different tab width. In any case, one should look at the diffs before each commit. This would have revealed those issues.


> *that was a mistake. Not sure what its role is though. I added .clear() also
> for the other vectors and maps. could not test it though.*

auxAtomInfos is a member variable, so old values could have remained in it when it is being filled with new values.


>  *Please check that it complies and that it works in the desired way
>  (especially lazy mode - regarding having added .clear() and having removed
>  the condition for cardinality cost. (As I changed my files to comply with
>  your folder structure Iḿ not able to compile it anymore)*

One test fails, but this is probably due to some gringo/clasp internals and not due to your changes. (It's just the order of solutions that is not as expected.)
In any case, please change lines 118-123 of test/IntegrationAspSolver.cpp to the following:

	EXPECT_EQ("Solutions:\n"
	          "\n"
	          "┣━ [1] a e r0 r1 r2 r3 r4 \n"
	          "┣━ [1] a c d r0 r1 r2 r3 r4 \n"
	          "┗━ [1] a b d r0 r1 r2 r3 r4 \n",
	          result);


Some other (hopefully) final remarks:

src/solver/asp/AtomIntroductionSolver.cpp

Please fix indentation.


src/solver/clasp/Solver.cpp

Please revert change (i.e., line 137 should be moved before the TODO) because nothing is really changed.


src/solver/lazy_default_join/Solver.cpp 

Please revert the changes on lines 77 and 134. (These lines should be in the code, but commented out.)

**Comment by mariusmoldovan** [comment]
Thanks as well. I've also done the last changes. Really hope it's fine now.

**Comment by bbliem** [comment]
Thanks. There were some syntax error in your show statements. I fixed this.

**Comment by mariusmoldovan** [comment]
Thanks!

**Pull request closed without merging**
