### PR TITLE
Functionality for built-in counters

### PR DESCRIPTION
**Pull request by mariusmoldovan**

### CODE REVIEW

**Comment by bbliem** [comment]
I have incorporated (most of) the changes in the new "counters" branch. Please review the changes and check that they make sense. For this, you may also want to look at a diff that compares my new "counters" branch to the code in your push request to see what I have changed. Also, I have not tested it much, so please check if the results are still correct.

I have made the following notable changes:

- Consistent indentation: I use tabs in my code instead of spaces. Unfortunately, your editor was set to use spaces, which made the diffs mostly useless.
- I do not store the cost of an item tree node in the list of counters. Reason: The "cost" counters are treated differently than other counters. For instance, we do not want to merge two rows if some counter has different values in these rows; but this does not hold for "cost": We do want to merge two rows that are identical except having a different cost value. Therefore, I retained methods like setCost().
- The previous change allows us to greatly simplify the code in ItemTreeNode::compareCostInsensitive, which may also improve performance.
- I removed code that is apparently not used, like solver::clasp::tables::ClaspCallback::counterAtomInfos.
- For instance in solver::clasp::tables::ClaspCallback, you only handled counters if optimization has not been disabled. However, counters except "cost" should also be handled if optimization is disabled. I changed this.

If this looks good, I will close the pull request.

**Comment by mariusmoldovan** [comment]
For now I noticed the following things which still need to be fixed:

- counterInc and cuurentCounterInc must have arity greater or equal to 2, but not necessarily equal to 2.
- D-FLAT --version does not show the version of the implementation.
- in the install file, the clasp version should be 3.1.4 not 3.1.3

Please let me know when you've done these changes (especially the first) so I can do some proper tests.

**Comment by mariusmoldovan** [comment]
Also: in ClaspCallback.cpp forFirstTrue should indeed work fine when considering (current)counterAtomInfos, but not (current)counterIncAtomInfos.

**Comment by bbliem** [comment]
Thanks, there is a new commit.

The `--version` argument should print the version just fine (but not 1.2.0 because I have not created the release yet).

**Comment by mariusmoldovan** [comment]
OK. Tests worked fine now. From my side, you can close the pull request. Thanks.

**Comment by bbliem** [comment]
Very good, thank you. I have moved the changes to the master branch (including your ASP encodings) and will make a release next.

**Pull request closed without merging**
